-- 센서 데이터 저장 테이블
-- 아두이노에서 전송된 센서 값들을 시간 순서대로 기록합니다.
CREATE TABLE sensor_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    device_id TEXT NOT NULL,
    temperature REAL,
    humidity REAL,
    soil_moisture REAL,
    light_intensity REAL
);
-- 센서 데이터 테이블에 대한 RLS(Row Level Security) 활성화
ALTER TABLE sensor_data ENABLE ROW LEVEL SECURITY;
-- 인증된 사용자만 센서 데이터를 읽을 수 있도록 정책 생성
CREATE POLICY "Allow authenticated users to read sensor data" ON sensor_data FOR
SELECT TO authenticated USING (true);
-- 액추에이터 상태 저장 테이블
-- 각 장치의 마지막 액추에이터(LED, 팬, 펌프) 상태를 저장합니다.
CREATE TABLE actuator_states (
    device_id TEXT PRIMARY KEY,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    led_on BOOLEAN DEFAULT false NOT NULL,
    fan_on BOOLEAN DEFAULT false NOT NULL,
    pump_on BOOLEAN DEFAULT false NOT NULL
);
-- 액추에이터 상태 테이블에 대한 RLS 활성화
ALTER TABLE actuator_states ENABLE ROW LEVEL SECURITY;
-- 인증된 사용자만 액추에이터 상태를 읽고 수정할 수 있도록 정책 생성
CREATE POLICY "Allow authenticated users to manage actuator states" ON actuator_states FOR ALL TO authenticated USING (true);